version: '3.8'

services:
  server:
   image: julianit0w/github-version-checker
   ports:
    - 443:3443
   volumes:
     - ./certs:/workspace/certs #HTTPS CERTIFICATES DIR FOR DOMAIN SET IN .env
   env_file:
    - .env